### ISSUE TITLE
precompiling after rails g serviceworker:install

### ISSUE THREAD

**Issue by seanpaulkelley** [rossta/serviceworker-rails#29] opened 2017-02-18 15:23 UTC
After installing on rails 4.2.7.1, all works in development.  When I precompile and push to production I see that serviceworker.js and manifest.json are getting precompiled correctly.  However, console log shows that site is asking for the serviceworker.js and manifest.json without fingerprint
/serviceworker.js:1 A bad HTTP response code (404) was received when fetching the script.

I have installed this gem before without issue.  This app is different than my previous install because it uses Cloudfront CDN for assets.  The other working app is also rails 5.0.1 and has in production.rb

```
 # Do not fallback to assets pipeline if a precompiled asset is missed.
 config.assets.compile = true
```
 Which I guess is not actually recommended for production so I will have to revisit that.

What would I need to change to get site to request precompiled version of these two files?

Here is my production.rb

```
Rails.application.configure do
  
  #minify js
  # Compress JavaScripts and CSS.
  config.assets.js_compressor = :uglifier
  config.assets.css_compressor = :sass
  config.assets.gzip = true

  # Settings specified here will take precedence over those in config/application.rb.

  # Code is not reloaded between requests.
  config.cache_classes = true

  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both threaded web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
  config.eager_load = true

  config.middleware.use Rack::Attack
  
  # Full error reports are disabled and caching is turned on.
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true

  # Enable Rack::Cache to put a simple HTTP cache in front of your application
  # Add `rack-cache` to your Gemfile before enabling this.
  # For large-scale production use, consider using a caching reverse proxy like
  # NGINX, varnish or squid.
  # config.action_dispatch.rack_cache = true

  # Disable serving static files from the `/public` folder by default since
  # Apache or NGINX already handles this.
  # handled now by gem 'rails_12factor', group: :production
  config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?
  config.font_assets.origin =  ENV['FONT_ASSETS_ORIGIN'] #'https://www.dressagestar.com'

  # Do not fallback to assets pipeline if a precompiled asset is missed.
  #config.assets.compile = true

  # Asset digests allow you to set far-future HTTP expiration dates on all assets,
  # yet still be able to expire them through the digest params.
  config.assets.digest = true
  config.static_cache_control = "public, max-age=#{1.month.to_i}"

  # Force all access to the app over SSL, use Strict-Transport-Security, and use secure cookies.
  config.force_ssl = true

  # Use the lowest log level to ensure availability of diagnostic information
  # when problems arise.
  config.log_level = :debug

  # Prepend all log lines with the following tags.
  # config.log_tags = [ :subdomain, :uuid ]

  # Use a different cache store in production.
  # config.cache_store = :mem_cache_store
  if ENV["MEMCACHEDCLOUD_SERVERS"]
    config.cache_store = :mem_cache_store, ENV["MEMCACHEDCLOUD_SERVERS"].split(','), { :username => ENV["MEMCACHEDCLOUD_USERNAME"], :password => ENV["MEMCACHEDCLOUD_PASSWORD"] }
  end

  # Enable serving of images, stylesheets, and JavaScripts from an asset server.
  # config.action_controller.asset_host = 'http://assets.example.com'
  config.action_controller.asset_host = ENV["CDN"]

  # added to improve google page speed insight's need for cached assets.  gets used by CDN
  config.static_cache_control = "public, max-age=#{1.week.to_i}"

  # Ignore bad email addresses and do not raise email delivery errors.
  # Set this to true and configure the email server for immediate delivery to raise delivery errors.
  # config.action_mailer.raise_delivery_errors = false

  # Enable locale fallbacks for I18n (makes lookups for any locale fall back to
  # the I18n.default_locale when a translation cannot be found).
  config.i18n.fallbacks = true

  # Send deprecation notices to registered listeners.
  config.active_support.deprecation = :notify

  # Use default logging formatter so that PID and timestamp are not suppressed.
  config.log_formatter = ::Logger::Formatter.new

  # Do not dump schema after migrations.
  config.active_record.dump_schema_after_migration = false
  
  # send mail later
  # config.active_job.queue_adapter = :sucker_punch
  # I care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false
  config.action_mailer.default_url_options = { :host => 'me.com' }
  
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: "smtp.sendgrid.net",
    port: "587",
    domain: "me.com",
    authentication: "plain",
	  user_name: ENV["SENDGRID_USERNAME"],
	  password: ENV["SENDGRID_PASSWORD"],
	  :enable_starttls_auto => true
  }	
  
end
```

**Comment by rossta** [comment] 2017-02-19 03:03
If you are precompiling assets, make sure that `config.assets.compile = false` or `nil` and not some truthy value. Assuming you have enabled the `serviceworker-rails` middleware [as described here](https://github.com/rossta/serviceworker-rails#configure-the-middleware), you do want the request to go to `/serviceworker.js`; the middleware will proxy the request to the fingerprinted-version assuming it exists on disk at the expected asset path (i.e., `public/assets/path/to/fingerprinted-serviceworker.js`)

**Comment by seanpaulkelley** [comment] 2017-02-23 00:51
hmmm
In production I have config.assets.compile = false

config/initializers/serviceworker.rb as generated by install process

`Rails.application.configure do
  config.serviceworker.routes.draw do
    # map to assets implicitly
    match "/serviceworker.js"
    match "/manifest.json"
  end
end`

I also verified that my fingerprinted js and manifest files are in public/assets

**Comment by rossta** [comment] 2017-02-23 04:02
If the middleware is enabled in production and the request for the serviceworker.js file matches the routes you've described above, then the key line is here: https://github.com/rossta/serviceworker-rails/blob/22b09fd1dd20552f41a14b92d447176f3924309c/lib/serviceworker/rails/handler.rb#L13.

If you can reproduce in a staging environment, perhaps you can troubleshoot whether the request hits that line before the 404 and debug the result; `path_info` is expected to be `/serviceworker.js` and the result of `asset_path(path_info)` should point to the fingerprinted serviceworker in the public directory.

**Comment by Mathews2115** [comment] 2017-04-10 16:13
@seanpaulkelley I know this is late but the issue you might be running into (This is for Rails 4, not 5) is there is a name collision with Rail 4 auto-created manifest.json (the file that holds a list of all your precompiled assets!!) and the web manifest.json!

Try renaming the manifest.json to webmanifest.json.  That was my issue!

Hope this helps!

**Comment by rossta** [comment] 2017-04-11 22:34
@Mathews2115 What version of sprockets are you on? This is supposed to be fixed in sprockets 3  https://github.com/rails/sprockets/issues/7

**Comment by Mathews2115** [comment] 2017-04-11 23:12
Indeed! It is fixed in 3 but the version I was using (didn't realize this until it was too late) was 2.  I think I got dinged with an older one due to an older ruby RVM and Rails 4.2.

**Comment by rossta** [comment] 2017-04-30 16:19
@seanpaulkelley I may have a fix for this. For now, try the `use_compute_asset_path` branch to get your serviceworker working in production.

**Closed** 2017-05-01 22:48 UTC

**Comment by rossta** [comment] 2017-05-02 03:40
You can now upgrade to `0.5.5` to resolve this issue.
